import { Container, MultiSelect, Tabs } from '@mantine/core';
import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react';
import { Favourites } from '../components/Favourites';
import { RepositoryList } from '../components/RepositoryList';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const [language, setLanguage] = useState<string[]>()

  const handleLanguageChange = (languages: string[]) => {
    setLanguage(languages);
  }

  const languages = [
    { value: 'javascript', label: 'Javascript' },
    { value: 'typescript', label: 'Typescript' },
    { value: 'ruby', label: 'Ruby' },
    { value: 'php', label: 'PHP' },
    { value: 'C#', label: 'C#' },
    { value: 'java', label: 'Java' },
    { value: 'python', label: 'Python' },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Github Trends for Veed.io</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <h1 className={styles.title}>
          Welcome to <a href="https://github.com" target={'_blank'} rel="noreferrer">Github Trends!</a>
        </h1>

        <p className={styles.description}>
          Here is the latest trending Github repositories{' '}
        </p>

        <Tabs variant={'outline'}>
          <Tabs.Tab label="Repositories">
            <MultiSelect
              value={language}
              data={languages}
              label="Filter by language"
              placeholder="Pick all that you like"
              onChange={handleLanguageChange}
            />
            <br />
            <RepositoryList languages={language}/>
          </Tabs.Tab>
          <Tabs.Tab label="Favorites">
            <Favourites />
          </Tabs.Tab>
        </Tabs>
        

      </Container>
    </div>
  )
}

export default Home
